spring:
  datasource:
    url: jdbc:mariadb://quiz2.cj6w8kog5kvm.ap-northeast-2.rds.amazonaws.com:3307/gp?serverTimezone=Asia/Seoul
    username: ${username}
    password: ${password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
  web:
    resources:
      static-locations: classpath:/static/
logging:
  level:
    root: info
    org:
      springframework:
        security:  DEBUG
server:
  port: 8080



